// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cart.proto

package cart

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddReq struct {
	UID                  uint64   `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	GoodID               uint64   `protobuf:"varint,2,opt,name=GoodID,proto3" json:"GoodID,omitempty"`
	Price                float64  `protobuf:"fixed64,3,opt,name=Price,proto3" json:"Price,omitempty"`
	GoodName             string   `protobuf:"bytes,4,opt,name=GoodName,proto3" json:"GoodName,omitempty"`
	Quantity             uint32   `protobuf:"varint,5,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReq) Reset()         { *m = AddReq{} }
func (m *AddReq) String() string { return proto.CompactTextString(m) }
func (*AddReq) ProtoMessage()    {}
func (*AddReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf731a5c8f9a516f, []int{0}
}

func (m *AddReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReq.Unmarshal(m, b)
}
func (m *AddReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReq.Marshal(b, m, deterministic)
}
func (m *AddReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReq.Merge(m, src)
}
func (m *AddReq) XXX_Size() int {
	return xxx_messageInfo_AddReq.Size(m)
}
func (m *AddReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddReq proto.InternalMessageInfo

func (m *AddReq) GetUID() uint64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *AddReq) GetGoodID() uint64 {
	if m != nil {
		return m.GoodID
	}
	return 0
}

func (m *AddReq) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *AddReq) GetGoodName() string {
	if m != nil {
		return m.GoodName
	}
	return ""
}

func (m *AddReq) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type AddResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResp) Reset()         { *m = AddResp{} }
func (m *AddResp) String() string { return proto.CompactTextString(m) }
func (*AddResp) ProtoMessage()    {}
func (*AddResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf731a5c8f9a516f, []int{1}
}

func (m *AddResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResp.Unmarshal(m, b)
}
func (m *AddResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResp.Marshal(b, m, deterministic)
}
func (m *AddResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResp.Merge(m, src)
}
func (m *AddResp) XXX_Size() int {
	return xxx_messageInfo_AddResp.Size(m)
}
func (m *AddResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddResp proto.InternalMessageInfo

type DelReq struct {
	ItemID               uint64   `protobuf:"varint,1,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelReq) Reset()         { *m = DelReq{} }
func (m *DelReq) String() string { return proto.CompactTextString(m) }
func (*DelReq) ProtoMessage()    {}
func (*DelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf731a5c8f9a516f, []int{2}
}

func (m *DelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelReq.Unmarshal(m, b)
}
func (m *DelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelReq.Marshal(b, m, deterministic)
}
func (m *DelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelReq.Merge(m, src)
}
func (m *DelReq) XXX_Size() int {
	return xxx_messageInfo_DelReq.Size(m)
}
func (m *DelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelReq proto.InternalMessageInfo

func (m *DelReq) GetItemID() uint64 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

type DelResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelResp) Reset()         { *m = DelResp{} }
func (m *DelResp) String() string { return proto.CompactTextString(m) }
func (*DelResp) ProtoMessage()    {}
func (*DelResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf731a5c8f9a516f, []int{3}
}

func (m *DelResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelResp.Unmarshal(m, b)
}
func (m *DelResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelResp.Marshal(b, m, deterministic)
}
func (m *DelResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelResp.Merge(m, src)
}
func (m *DelResp) XXX_Size() int {
	return xxx_messageInfo_DelResp.Size(m)
}
func (m *DelResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelResp proto.InternalMessageInfo

type UpdateReq struct {
	ItemID               uint64   `protobuf:"varint,1,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
	Quantity             uint32   `protobuf:"varint,2,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReq) Reset()         { *m = UpdateReq{} }
func (m *UpdateReq) String() string { return proto.CompactTextString(m) }
func (*UpdateReq) ProtoMessage()    {}
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf731a5c8f9a516f, []int{4}
}

func (m *UpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReq.Unmarshal(m, b)
}
func (m *UpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReq.Marshal(b, m, deterministic)
}
func (m *UpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReq.Merge(m, src)
}
func (m *UpdateReq) XXX_Size() int {
	return xxx_messageInfo_UpdateReq.Size(m)
}
func (m *UpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReq proto.InternalMessageInfo

func (m *UpdateReq) GetItemID() uint64 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

func (m *UpdateReq) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type UpdateResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResp) Reset()         { *m = UpdateResp{} }
func (m *UpdateResp) String() string { return proto.CompactTextString(m) }
func (*UpdateResp) ProtoMessage()    {}
func (*UpdateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf731a5c8f9a516f, []int{5}
}

func (m *UpdateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResp.Unmarshal(m, b)
}
func (m *UpdateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResp.Marshal(b, m, deterministic)
}
func (m *UpdateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResp.Merge(m, src)
}
func (m *UpdateResp) XXX_Size() int {
	return xxx_messageInfo_UpdateResp.Size(m)
}
func (m *UpdateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResp proto.InternalMessageInfo

type DelAllReq struct {
	UID                  uint64   `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelAllReq) Reset()         { *m = DelAllReq{} }
func (m *DelAllReq) String() string { return proto.CompactTextString(m) }
func (*DelAllReq) ProtoMessage()    {}
func (*DelAllReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf731a5c8f9a516f, []int{6}
}

func (m *DelAllReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelAllReq.Unmarshal(m, b)
}
func (m *DelAllReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelAllReq.Marshal(b, m, deterministic)
}
func (m *DelAllReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelAllReq.Merge(m, src)
}
func (m *DelAllReq) XXX_Size() int {
	return xxx_messageInfo_DelAllReq.Size(m)
}
func (m *DelAllReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelAllReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelAllReq proto.InternalMessageInfo

func (m *DelAllReq) GetUID() uint64 {
	if m != nil {
		return m.UID
	}
	return 0
}

type DelAllResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelAllResp) Reset()         { *m = DelAllResp{} }
func (m *DelAllResp) String() string { return proto.CompactTextString(m) }
func (*DelAllResp) ProtoMessage()    {}
func (*DelAllResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf731a5c8f9a516f, []int{7}
}

func (m *DelAllResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelAllResp.Unmarshal(m, b)
}
func (m *DelAllResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelAllResp.Marshal(b, m, deterministic)
}
func (m *DelAllResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelAllResp.Merge(m, src)
}
func (m *DelAllResp) XXX_Size() int {
	return xxx_messageInfo_DelAllResp.Size(m)
}
func (m *DelAllResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelAllResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelAllResp proto.InternalMessageInfo

type DisplayReq struct {
	UID                  uint64   `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisplayReq) Reset()         { *m = DisplayReq{} }
func (m *DisplayReq) String() string { return proto.CompactTextString(m) }
func (*DisplayReq) ProtoMessage()    {}
func (*DisplayReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf731a5c8f9a516f, []int{8}
}

func (m *DisplayReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisplayReq.Unmarshal(m, b)
}
func (m *DisplayReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisplayReq.Marshal(b, m, deterministic)
}
func (m *DisplayReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisplayReq.Merge(m, src)
}
func (m *DisplayReq) XXX_Size() int {
	return xxx_messageInfo_DisplayReq.Size(m)
}
func (m *DisplayReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DisplayReq.DiscardUnknown(m)
}

var xxx_messageInfo_DisplayReq proto.InternalMessageInfo

func (m *DisplayReq) GetUID() uint64 {
	if m != nil {
		return m.UID
	}
	return 0
}

type DisplayResp struct {
	UID                  uint64   `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Items                []*Item  `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisplayResp) Reset()         { *m = DisplayResp{} }
func (m *DisplayResp) String() string { return proto.CompactTextString(m) }
func (*DisplayResp) ProtoMessage()    {}
func (*DisplayResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf731a5c8f9a516f, []int{9}
}

func (m *DisplayResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisplayResp.Unmarshal(m, b)
}
func (m *DisplayResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisplayResp.Marshal(b, m, deterministic)
}
func (m *DisplayResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisplayResp.Merge(m, src)
}
func (m *DisplayResp) XXX_Size() int {
	return xxx_messageInfo_DisplayResp.Size(m)
}
func (m *DisplayResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DisplayResp.DiscardUnknown(m)
}

var xxx_messageInfo_DisplayResp proto.InternalMessageInfo

func (m *DisplayResp) GetUID() uint64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *DisplayResp) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Item struct {
	ItemID               uint64   `protobuf:"varint,1,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
	GoodID               uint64   `protobuf:"varint,2,opt,name=GoodID,proto3" json:"GoodID,omitempty"`
	Price                float64  `protobuf:"fixed64,3,opt,name=Price,proto3" json:"Price,omitempty"`
	GoodName             string   `protobuf:"bytes,4,opt,name=GoodName,proto3" json:"GoodName,omitempty"`
	Quantity             uint32   `protobuf:"varint,5,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	CreateTime           int64    `protobuf:"varint,6,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	ModifyTime           int64    `protobuf:"varint,7,opt,name=ModifyTime,proto3" json:"ModifyTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf731a5c8f9a516f, []int{10}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetItemID() uint64 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

func (m *Item) GetGoodID() uint64 {
	if m != nil {
		return m.GoodID
	}
	return 0
}

func (m *Item) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Item) GetGoodName() string {
	if m != nil {
		return m.GoodName
	}
	return ""
}

func (m *Item) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Item) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Item) GetModifyTime() int64 {
	if m != nil {
		return m.ModifyTime
	}
	return 0
}

func init() {
	proto.RegisterType((*AddReq)(nil), "cart.AddReq")
	proto.RegisterType((*AddResp)(nil), "cart.AddResp")
	proto.RegisterType((*DelReq)(nil), "cart.DelReq")
	proto.RegisterType((*DelResp)(nil), "cart.DelResp")
	proto.RegisterType((*UpdateReq)(nil), "cart.UpdateReq")
	proto.RegisterType((*UpdateResp)(nil), "cart.UpdateResp")
	proto.RegisterType((*DelAllReq)(nil), "cart.DelAllReq")
	proto.RegisterType((*DelAllResp)(nil), "cart.DelAllResp")
	proto.RegisterType((*DisplayReq)(nil), "cart.DisplayReq")
	proto.RegisterType((*DisplayResp)(nil), "cart.DisplayResp")
	proto.RegisterType((*Item)(nil), "cart.Item")
}

func init() { proto.RegisterFile("cart.proto", fileDescriptor_bf731a5c8f9a516f) }

var fileDescriptor_bf731a5c8f9a516f = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0xd1, 0x4a, 0xf3, 0x30,
	0x1c, 0xc5, 0x97, 0xb5, 0xeb, 0xbe, 0xfe, 0xb7, 0xf1, 0xcd, 0x20, 0xa3, 0x14, 0x1c, 0x21, 0x78,
	0xd1, 0x1b, 0x87, 0xcc, 0x07, 0x90, 0xb2, 0x82, 0xec, 0x42, 0xd1, 0xea, 0x1e, 0xa0, 0xae, 0x11,
	0x0a, 0x9d, 0x8d, 0x4d, 0x14, 0x76, 0xe7, 0xc3, 0xf9, 0x32, 0xbe, 0x85, 0xa4, 0x59, 0xe2, 0x36,
	0xa6, 0x97, 0xde, 0xe5, 0x9c, 0xf3, 0xdb, 0xf2, 0x4f, 0x4e, 0x0a, 0xb0, 0xcc, 0x6a, 0x39, 0xe1,
	0x75, 0x25, 0x2b, 0xec, 0xaa, 0x35, 0x7d, 0x47, 0xe0, 0xc5, 0x79, 0x9e, 0xb2, 0x17, 0x3c, 0x04,
	0x67, 0x31, 0x4f, 0x02, 0x44, 0x50, 0xe4, 0xa6, 0x6a, 0x89, 0x47, 0xe0, 0x5d, 0x55, 0x55, 0x3e,
	0x4f, 0x82, 0x76, 0x63, 0x6e, 0x14, 0x3e, 0x86, 0xce, 0x6d, 0x5d, 0x2c, 0x59, 0xe0, 0x10, 0x14,
	0xa1, 0x54, 0x0b, 0x1c, 0xc2, 0x3f, 0x95, 0xdf, 0x64, 0x2b, 0x16, 0xb8, 0x04, 0x45, 0x7e, 0x6a,
	0xb5, 0xca, 0xee, 0x5e, 0xb3, 0x67, 0x59, 0xc8, 0x75, 0xd0, 0x21, 0x28, 0x1a, 0xa4, 0x56, 0x53,
	0x1f, 0xba, 0xcd, 0x04, 0x82, 0x53, 0x02, 0x5e, 0xc2, 0x4a, 0x35, 0xcc, 0x08, 0xbc, 0xb9, 0x64,
	0x2b, 0x3b, 0xcf, 0x46, 0x29, 0xb8, 0x21, 0x04, 0xa7, 0x97, 0xe0, 0x2f, 0x78, 0x9e, 0x49, 0xf6,
	0x0b, 0xbf, 0xb3, 0x71, 0x7b, 0x6f, 0xe3, 0x3e, 0x80, 0xf9, 0x03, 0xc1, 0xe9, 0x09, 0xf8, 0x09,
	0x2b, 0xe3, 0xb2, 0x3c, 0x78, 0x17, 0x0a, 0x36, 0xb1, 0xe0, 0x74, 0x0c, 0x90, 0x14, 0x82, 0x97,
	0xd9, 0xfa, 0x30, 0x1d, 0x43, 0xcf, 0xe6, 0x82, 0x1f, 0xb8, 0x5a, 0x02, 0x1d, 0x35, 0xa1, 0x08,
	0xda, 0xc4, 0x89, 0x7a, 0x53, 0x98, 0x34, 0xcd, 0x28, 0x2b, 0xd5, 0x01, 0xfd, 0x40, 0xe0, 0xaa,
	0xd5, 0x8f, 0x47, 0xfb, 0x93, 0x76, 0xf0, 0x18, 0x60, 0x56, 0xb3, 0x4c, 0xb2, 0x87, 0x62, 0xc5,
	0x02, 0x8f, 0xa0, 0xc8, 0x49, 0xb7, 0x1c, 0x95, 0x5f, 0x57, 0x79, 0xf1, 0xb4, 0x6e, 0xf2, 0xae,
	0xce, 0xbf, 0x9d, 0xe9, 0x27, 0x82, 0xde, 0x2c, 0xab, 0xe5, 0x3d, 0xab, 0xdf, 0xd4, 0x1c, 0xa7,
	0xe0, 0xc4, 0x79, 0x8e, 0xfb, 0xfa, 0xc0, 0xfa, 0xe9, 0x85, 0x83, 0x2d, 0x25, 0x38, 0x6d, 0x29,
	0x2a, 0x61, 0xa5, 0xa1, 0xf4, 0x9b, 0x30, 0x94, 0xe9, 0xbf, 0x85, 0xcf, 0xc0, 0xd3, 0x05, 0xe2,
	0xff, 0x3a, 0xb2, 0xef, 0x21, 0x1c, 0xee, 0x1a, 0x06, 0xd7, 0x15, 0x1a, 0xdc, 0xf6, 0x6d, 0xf0,
	0xad, 0x86, 0x5b, 0xf8, 0x1c, 0xba, 0x9b, 0x0e, 0xb1, 0x89, 0x6d, 0xe5, 0xe1, 0xd1, 0x9e, 0xa3,
	0x7e, 0xf1, 0xe8, 0x35, 0x5f, 0xd6, 0xc5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0x72, 0x4d,
	0x3a, 0x67, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CartServiceClient is the client API for CartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CartServiceClient interface {
	Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddResp, error)
	Del(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*DelResp, error)
	Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*UpdateResp, error)
	DelAll(ctx context.Context, in *DelAllReq, opts ...grpc.CallOption) (*DelAllResp, error)
	Display(ctx context.Context, in *DisplayReq, opts ...grpc.CallOption) (*DisplayResp, error)
}

type cartServiceClient struct {
	cc *grpc.ClientConn
}

func NewCartServiceClient(cc *grpc.ClientConn) CartServiceClient {
	return &cartServiceClient{cc}
}

func (c *cartServiceClient) Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddResp, error) {
	out := new(AddResp)
	err := c.cc.Invoke(ctx, "/cart.CartService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) Del(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*DelResp, error) {
	out := new(DelResp)
	err := c.cc.Invoke(ctx, "/cart.CartService/Del", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*UpdateResp, error) {
	out := new(UpdateResp)
	err := c.cc.Invoke(ctx, "/cart.CartService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) DelAll(ctx context.Context, in *DelAllReq, opts ...grpc.CallOption) (*DelAllResp, error) {
	out := new(DelAllResp)
	err := c.cc.Invoke(ctx, "/cart.CartService/DelAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) Display(ctx context.Context, in *DisplayReq, opts ...grpc.CallOption) (*DisplayResp, error) {
	out := new(DisplayResp)
	err := c.cc.Invoke(ctx, "/cart.CartService/Display", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartServiceServer is the server API for CartService service.
type CartServiceServer interface {
	Add(context.Context, *AddReq) (*AddResp, error)
	Del(context.Context, *DelReq) (*DelResp, error)
	Update(context.Context, *UpdateReq) (*UpdateResp, error)
	DelAll(context.Context, *DelAllReq) (*DelAllResp, error)
	Display(context.Context, *DisplayReq) (*DisplayResp, error)
}

func RegisterCartServiceServer(s *grpc.Server, srv CartServiceServer) {
	s.RegisterService(&_CartService_serviceDesc, srv)
}

func _CartService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cart.CartService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).Add(ctx, req.(*AddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cart.CartService/Del",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).Del(ctx, req.(*DelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cart.CartService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).Update(ctx, req.(*UpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_DelAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).DelAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cart.CartService/DelAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).DelAll(ctx, req.(*DelAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_Display_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisplayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).Display(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cart.CartService/Display",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).Display(ctx, req.(*DisplayReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _CartService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cart.CartService",
	HandlerType: (*CartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _CartService_Add_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _CartService_Del_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CartService_Update_Handler,
		},
		{
			MethodName: "DelAll",
			Handler:    _CartService_DelAll_Handler,
		},
		{
			MethodName: "Display",
			Handler:    _CartService_Display_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cart.proto",
}
